export { default as SplashScreen } from './Splash';
export { default as HomeScreen } from './Home';
export { default as MovieScreen } from './Movie';
export { default as ScreeningsScreen } from './Screenings';
export { default as ChockoutScreen } from './Checkout';
export { default as SearchScreen } from './Search';
export { default as PersonalAreaScreen } from './Personal Area';
export { default as TicketScreen } from './Ticket';
export { default as CancelationScreen } from './Cancelation';
export { default as EditProfileScreen } from './Edit Profile';